# Generated by Django 2.2 on 2019-04-10 12:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190410_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
