# Generated by Django 2.2 on 2019-04-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190411_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
